CRITICAL - 2023-01-21 19:05:21 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 224.
 1 SYSTEMPATH\CodeIgniter.php(224): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(182): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-01-21 19:05:24 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 224.
 1 SYSTEMPATH\CodeIgniter.php(224): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(182): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
ERROR - 2023-01-21 12:06:13 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'tercera_mano' in C:\xampp\htdocs\terceraMano\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 C:\xampp\htdocs\terceraMano\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'tercera_mano', 3306, '', 0)
#1 C:\xampp\htdocs\terceraMano\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\terceraMano\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\terceraMano\app\Models\modelo.php(22): CodeIgniter\Database\BaseConnection->query('SELECT nombre f...')
#4 C:\xampp\htdocs\terceraMano\app\Controllers\Home.php(21): App\Models\Modelo->nombreUsuario(NULL)
#5 C:\xampp\htdocs\terceraMano\system\CodeIgniter.php(927): App\Controllers\Home->index()
#6 C:\xampp\htdocs\terceraMano\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\terceraMano\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\terceraMano\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'tercera_mano' in C:\xampp\htdocs\terceraMano\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\terceraMano\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\terceraMano\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\terceraMano\app\Models\modelo.php(22): CodeIgniter\Database\BaseConnection->query('SELECT nombre f...')
#3 C:\xampp\htdocs\terceraMano\app\Controllers\Home.php(21): App\Models\Modelo->nombreUsuario(NULL)
#4 C:\xampp\htdocs\terceraMano\system\CodeIgniter.php(927): App\Controllers\Home->index()
#5 C:\xampp\htdocs\terceraMano\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\terceraMano\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\terceraMano\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-01-21 12:06:13 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'tercera_mano'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\modelo.php(22): CodeIgniter\Database\BaseConnection->query('SELECT nombre from usuarios where cod_usuario=\'\';')
 3 APPPATH\Controllers\Home.php(21): App\Models\Modelo->nombreUsuario(null)
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Home->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
